[colors]
[colors.primary]
background = "#1e1e2e"
foreground = "#cdd6f4"

[colors.normal]
black   = "#1e1e2e"
red     = "#2a2a3b"
green   = "#353748"
yellow  = "#414356"
blue    = "#4d4f63"
magenta = "#585b70"
cyan    = "#64687d"
white   = "#70748a"

[colors.bright]
black   = "#7b8098"
red     = "#878ca5"
green   = "#9399b2"
yellow  = "#9ea5bf"
blue    = "#aab1cc"
magenta = "#b6bdda"
cyan    = "#c1cae7"
white   = "#cdd6f4"

[colors.cursor]
text   = "#1e1e2e"
cursor = "#cdd6f4"
